version: '3.1'
services:
  nginx:
    restart: always
    build:
      context: ./nginx
    ports: 
      - '80:80'
  auth:
    build:
      context: ./auth
    ports: 
      - '3000:3000'
  prediction:
    build:
      context: ./prediction
    ports:
      - '5000:5000'